name: my_emulator_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  # Other packages
  file_picker: ^10.3.6
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.2
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  url_launcher: ^6.3.2
  web: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
